### PR TITLE
Create monty-hall.md

### PR DESCRIPTION
**Pull request by chrisranderson**
I don't know how much you're looking for new examples, but I thought this one might be fun. No worries at all if you'd prefer not to include it.

### CODE REVIEW

**Comment by stuhlmueller** [comment]
That's cool!

**Comment by chrisranderson** [comment]
I think I'll count this as my first publication. :)

**Comment by longouyang** [comment]
You forgot to cite us ;) https://probmods.org/inference-about-inference.html#exercises

**Comment by chrisranderson** [comment]
Independent discovery :)

Currently on chapter 5. Haha. That's a good one.

**Pull request merged**
